### ISSUE TITLE
Question regarding default currency value

### ISSUE THREAD

**Issue by smithaammassamveettil** [rubicon-project/prebid-server-java#678]
How do we configure the default currency value, if the bid request from publisher doesn't contain the currency? Noticed the below place it is setting it as null
https://github.com/rubicon-project/prebid-server-java/blob/master/src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java#L169

I tried testing by setting this value to "USD" instead of null. It is working. Otherwise receiving below error
"Invalid request format: currency was not defined either in request.cur or in configuration field adServerCurrency" while testing.

What is the expected way to set this default value? Are we supposed to validate and add default in each adapter code if bidrequest.cur is not present?

@DGarbar  Please let me know.

**Comment by DGarbar** [comment]
Host of the Prebid server can configure `auction.ad-server-currency` value in `application.yaml`. 
This value will be used only for auction requests that missing `req.cur`.

**Comment by smithaammassamveettil** [comment]
@DGarbar  A few more questions to understand it better:
1 ) Is this application.yaml file per adapter or one for all prebid server? (I didnt see in the existing application.yaml file, it is defined anywhere)
2) Whats its default value currently, which you configured for Prebid server? 
3) So as per your above statement, I dont need to make any changes in brightroll adapter or dont need to do any specific configuration in the adapter right?

**Comment by rpanchyk** [comment]
hi @smithaammassamveettil !
1) `application.yaml` config is global for prebid server.
2) [auction.ad-server-currency](https://github.com/rubicon-project/prebid-server-java/blob/master/docs/config-app.md#auction-openrtb) is not defined by default. Each host company will set its own. For example, Rubicon-hosted PBS uses `USD`.
3) No additional configuration required for any bidder in scope of default currency.

Just want to pay your attention, all received bids from Brightroll exchange will be assumed in `USD` - https://github.com/rubicon-project/prebid-server-java/blob/master/src/main/java/org/prebid/server/bidder/brightroll/BrightrollBidder.java#L250 (bid currency is passed as `null`):
```
.map(bid -> BidderBid.of(bid, getBidderType(imps, bid.getImpid()), null))
```

Since our currency converter uses hardcoded default `USD` - https://github.com/rubicon-project/prebid-server-java/blob/master/src/main/java/org/prebid/server/currency/CurrencyConversionService.java#L134
```
// use Default USD currency if bidder left this field empty. After, when bidder will implement multi currency
// support it will be changed to throwing PrebidException.
final String effectiveBidCurrency = bidCurrency != null ? bidCurrency : DEFAULT_BID_CURRENCY;
```

**Comment by rpanchyk** [comment]
@smithaammassamveettil any other details? Or we can close this?

**Comment by rpanchyk** [comment]
Closing. Please reopen if any questions.
