### ISSUE TITLE
Refactor metrics

### ISSUE THREAD

**Issue by bretg** [rubicon-project/prebid-server-java#81]
Looking at the account-level metrics for PBS-Java, it's apparent that AMP requests aren't logging the same set of metrics as regular openrtb requests. 

The first step is to catch up with what's being done on the Go side in https://github.com/prebid/prebid-server/pull/547 and https://github.com/prebid/prebid-server/pull/550. Then we should go beyond the Go implementation to count adapter and account requests. Also, Go

Scenarios:

- openrtb (with or without stored requests)
- openrtb for app (with or without stored requests) 
- AMP

Every request should log:

- $.{ok,badinput,err}.{ortb-web,ortb-app,amp,legacy}
- $.adapter.ID.requests.type.{ortb-web,ortb-app,amp,legacy} 
  - this is https://github.com/prebid/prebid-server/issues/551

Make the following metric configurable:
- $.account.ID.requests.type.{ortb-web,ortb-app,amp,legacy}

Suggested configuration:
{code}
metrics.accounts.default: {none, basic, detailed}
metrics.accounts.basic: acctId1, accId2
metrics.accounts.detailed: acctId3, accId4
{code}
Where 'basic' metrics are:
- account.ID.requests
- account.ID.bids_received
And 'detailed' metrics are everything else:
- account.ID.ADAPTER.*
- account.ID.requests.type.\{ortb-web,ortb-app,amp,legacy\}

If either 'basic' or 'detailed' is specified in the config and an account is not in either 'basic' or 'detailed', no metrics should be logged for it.

Other changes aligning with https://github.com/prebid/prebid-server/pull/550:
```
requests.adapter.ID.requests.gotbids => a bid request was made and bids were returned
requests.adapter.ID.requests.nobid => a bid request was made, but no bids were returned
requests.adapter.ID.requests.badinput => a bid request was made with some invalid input
requests.adapter.ID.requests.badserverresponse => a bid request was made and the server responded with an error or something unexpected.
requests.adapter.ID.requests.timeout => a bid request was made and the bidder timed out.
requests.adapter.ID.requests.unknown => a bid request was made and some unknown error happened.
```

**Comment by jordillachmrf** [comment]
Taking advantatge of this issue I would like to ask if we could take into consideration the following :
- do not track all the requests, just a %
- be able to TOTALLY disable metrics

The latter could be very useful because we could launch two instances of prebid-server and just gather metrics in one of them.

**Comment by bretg** [comment]
> be able to TOTALLY disable metrics

That's easy enough today -- just don't include the `metrics` section of the server config.

> do not track all the requests, just a %

Which percentages? e.g. percent AMP requests? What's the goal of logging percentages -- saving metrics space? With multiple servers, percentages can't add.

**Comment by jordillachmrf** [comment]
It's a matter of performance although I do not configure anything the code is still being executed, and all those counters are increased for each request
About percentages ... the same reason ... performance

This week I've been at JBcnConf and you could not imagine what companies like DynaTrace are doing in order to avoid incrementing counters whenever possible, the talk was quite awesome http://www.jbcnconf.com/2018/infoTalk.html?id=33

**Comment by schernysh** [comment]
Hi @jordillachmrf.

Since this issue is focused mostly on improvements related to what metrics to collect let's tackle your suggestion as separate issue (or maybe issues?). Please feel free to create them to start discussion.
